CREATE TABLE dbo.Student (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(255) NOT NULL,
    DateOfBirth DATE NOT NULL,
    ClassRoomId INT NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    CreatedBy NVARCHAR(255) NOT NULL,
    UpdatedBy NVARCHAR(255) NOT NULL,
    CONSTRAINT FK_Student_ClassRoom FOREIGN KEY (ClassRoomId) REFERENCES dbo.ClassRoom(Id) ON DELETE CASCADE 
);
