CREATE TABLE dbo.Teacher (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(255) NOT NULL,
    Subject NVARCHAR(255) NOT NULL,
    ClassRoomId INT NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    CreatedBy NVARCHAR(255) NOT NULL,
    UpdatedBy NVARCHAR(255) NOT NULL,
    CONSTRAINT FK_Teacher_ClassRoom FOREIGN KEY (ClassRoomId) REFERENCES dbo.ClassRoom(Id) ON DELETE CASCADE 
);
